### ISSUE TITLE
re-declaration of module

### ISSUE THREAD

**Issue by bsr203** [jeffmay/angular-ts-seed#1]
A question to understand the rationale behind `redeclaring` the module as in common-services.ts. I do not concat the files until at the end, and if look at the individual js file, I see modules are redeclared 
in `common-service.js` and `all-modules.js` as

```
var modules;
//module pattern
```

 Why can't we just do 

```
modules.services.common.service("uuid", () => new NodeUUIDGenerator())
```

in common-service.ts?

Well, I do not use a concatenated single file until distribution. I am afraid having a single js file may increase the compilation time significantly as number of file increases (say in hundreds). Do you think so?

**Comment by basarat** [comment]
> I am afraid having a single js file may increase the compilation time significantly as number of file increases (say in hundreds)

It will not matter at the moment if you use a `reference.ts`. The difference b/w `--out` vs `--outDir` is simply in single file vs. bunch of files but the compiler looks at all the files because of `reference.ts`. However there is a plan is to make it faster when compiling without `--out` : https://github.com/grunt-ts/grunt-ts/issues/34

**Comment by bsr203** [comment]
thank you for the response. Actually, I initially was using grunt-typescript with watch and only pass the changed file to the grunt job like

```
//Only recompile the ts files that have actually changed.
    var onChange = grunt.util._.debounce(function () {
        grunt.config('typescript.base.src', Object.keys(changedFiles));
        changedFiles = Object.create(null);
    }, 200);
    grunt.event.on('watch', function (action, filepath) {
        changedFiles[filepath] = action;
        onChange();
    });

```

now, I am moving over to grunt-ts. So, do you mean, typescript compiler is smart enough to only process the change, or if I do not change the target as above no diff between single vs multi files. Do you think I can save compile time if I use watch as above, with your grunt plugin (grunt-ts).  It is an issue I need to think about as I am trying convert a decent size js project to ts.  

thanks again for your help.

**Comment by bsr203** [comment]
compiling a single file worked with `grunt-ts` through just feeding the changed file as above.

```
>> File "app/scripts/ae/modules.ts" changed.


Running "ts:app" (ts) task
Compiling...
Using tsc v0.9.5
conf { src: [ 'app/scripts/ae/reference.ts' ],
  html: [ 'app/scripts/ae/**/*.html' ],
  reference: 'app/scripts/ae/reference.ts',
  out: 'app/js/app.js' }

Success: 2.66s for 1 typescript files
```

hope it maintains the same compile time as the program scales.

**Comment by jeffmay** [comment]
> Why can't we just do
>     modules.services.common.service("uuid", () => new NodeUUIDGenerator())

You can. In fact, with chaining that might be a better way to do it.

The reason for declaring it twice is so you can use module names by reference and avoid cyclical dependencies. The only issue with using module names is that you have to reorder the modules when dependencies change.

However, if you name all the modules first, then you can rearrange the dependencies without having to move the bindings. I felt this was an interesting way to prevent cyclical dependencies at compile-time without clobbering your git history when dependencies change.

That being said, it is totally find to have a single file for each module and use string names to reference service dependencies. Alternatively, you can use module names to build your dependencies and just change the order of the modules in the `reference.ts` so that the module references are all defined by the point where you reference their names.

**Comment by jeffmay** [comment]
@bsr203 did this answer your questions? Please reopen if you have any other issues.

**Comment by bsr203** [comment]
thanks Jeff. I am still trying to set it all up. Will respond if any question. Thanks again for your help.
